-- RBAC Setup for Inventory Management System
-- ===========================================
--
-- This SQL must be run manually in the Supabase SQL Editor BEFORE the application
-- will work. It sets up:
-- 1. The app_role enum and user_roles table
-- 2. The custom_access_token_hook function (injects role into JWT)
-- 3. The authorize() function for RLS policies
-- 4. RLS policies for all application tables
--
-- After running this SQL:
-- 1. Go to Supabase Dashboard -> Authentication -> Hooks
-- 2. Enable "Customize Access Token (JWT) Claims"
-- 3. Select the custom_access_token_hook function
-- 4. Save
--
-- Then run the Prisma seed script to create the initial admin user.

-- ============================================
-- 1. Role type and user_roles table
-- ============================================

CREATE TYPE public.app_role AS ENUM ('admin', 'staff', 'viewer');

CREATE TABLE public.user_roles (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id   UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  role      app_role NOT NULL,
  UNIQUE (user_id, role)
);

-- Enable RLS on user_roles
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

-- ============================================
-- 2. Custom Access Token Hook
-- ============================================
-- This function is called by Supabase Auth on every token refresh.
-- It injects the user_role claim into the JWT.

CREATE OR REPLACE FUNCTION public.custom_access_token_hook(event jsonb)
RETURNS jsonb
LANGUAGE plpgsql STABLE
SECURITY DEFINER
SET search_path = 'public'
AS $$
DECLARE
  claims jsonb;
  user_role public.app_role;
BEGIN
  SELECT role INTO user_role FROM public.user_roles
  WHERE user_id = (event->>'user_id')::uuid;

  claims := event->'claims';
  IF user_role IS NOT NULL THEN
    claims := jsonb_set(claims, '{user_role}', to_jsonb(user_role));
  ELSE
    claims := jsonb_set(claims, '{user_role}', '"viewer"');
  END IF;

  event := jsonb_set(event, '{claims}', claims);
  RETURN event;
END;
$$;

-- Grant execute to supabase_auth_admin (required for the hook)
GRANT EXECUTE ON FUNCTION public.custom_access_token_hook TO supabase_auth_admin;

-- Revoke from public roles for security
REVOKE EXECUTE ON FUNCTION public.custom_access_token_hook FROM public;
REVOKE EXECUTE ON FUNCTION public.custom_access_token_hook FROM anon;
REVOKE EXECUTE ON FUNCTION public.custom_access_token_hook FROM authenticated;

-- Grant usage on the app_role type
GRANT USAGE ON TYPE public.app_role TO supabase_auth_admin;

-- Grant read access on user_roles to supabase_auth_admin (needed by the hook to query roles)
GRANT SELECT ON TABLE public.user_roles TO supabase_auth_admin;

-- ============================================
-- 3. Authorize function for RLS policies
-- ============================================
-- Checks if the current JWT contains a role >= the requested role.

CREATE OR REPLACE FUNCTION public.authorize(requested_role app_role)
RETURNS boolean AS $$
DECLARE
  user_role public.app_role;
BEGIN
  SELECT (auth.jwt() ->> 'user_role')::public.app_role INTO user_role;

  -- Admin can do everything
  IF user_role = 'admin' THEN RETURN true; END IF;
  -- Staff can do staff and viewer things
  IF user_role = 'staff' AND requested_role IN ('staff', 'viewer') THEN RETURN true; END IF;
  -- Viewer can only do viewer things
  IF user_role = 'viewer' AND requested_role = 'viewer' THEN RETURN true; END IF;

  RETURN false;
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = '';

-- ============================================
-- 4. RLS Policies for user_roles
-- ============================================

-- Admin can read all roles
CREATE POLICY "user_roles_select_admin" ON public.user_roles
  FOR SELECT TO authenticated
  USING ((SELECT public.authorize('admin')));

-- Admin can insert roles
CREATE POLICY "user_roles_insert_admin" ON public.user_roles
  FOR INSERT TO authenticated
  WITH CHECK ((SELECT public.authorize('admin')));

-- Admin can update roles
CREATE POLICY "user_roles_update_admin" ON public.user_roles
  FOR UPDATE TO authenticated
  USING ((SELECT public.authorize('admin')));

-- Admin can delete roles
CREATE POLICY "user_roles_delete_admin" ON public.user_roles
  FOR DELETE TO authenticated
  USING ((SELECT public.authorize('admin')));

-- ============================================
-- 5. RLS Policies for items table
-- ============================================

ALTER TABLE public.items ENABLE ROW LEVEL SECURITY;

-- All authenticated users can read items (viewer+)
CREATE POLICY "items_select" ON public.items
  FOR SELECT TO authenticated
  USING ((SELECT public.authorize('viewer')));

-- Staff and admin can insert items
CREATE POLICY "items_insert" ON public.items
  FOR INSERT TO authenticated
  WITH CHECK ((SELECT public.authorize('staff')));

-- Staff and admin can update items (including soft-delete)
CREATE POLICY "items_update" ON public.items
  FOR UPDATE TO authenticated
  USING ((SELECT public.authorize('staff')));

-- No hard delete policy -- use soft-delete (update deleted_at) instead

-- ============================================
-- 6. RLS Policies for inventory_transactions
-- ============================================

ALTER TABLE public.inventory_transactions ENABLE ROW LEVEL SECURITY;

-- All authenticated users can read transactions (viewer+)
CREATE POLICY "inventory_transactions_select" ON public.inventory_transactions
  FOR SELECT TO authenticated
  USING ((SELECT public.authorize('viewer')));

-- Staff and admin can insert transactions
CREATE POLICY "inventory_transactions_insert" ON public.inventory_transactions
  FOR INSERT TO authenticated
  WITH CHECK ((SELECT public.authorize('staff')));

-- No update or delete -- ledger is append-only

-- ============================================
-- 7. RLS Policies for profiles
-- ============================================

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- All authenticated users can read profiles (viewer+)
CREATE POLICY "profiles_select" ON public.profiles
  FOR SELECT TO authenticated
  USING ((SELECT public.authorize('viewer')));

-- Users can update their own profile only
CREATE POLICY "profiles_update_own" ON public.profiles
  FOR UPDATE TO authenticated
  USING (id = auth.uid());

-- Admin can insert profiles (for user creation)
CREATE POLICY "profiles_insert_admin" ON public.profiles
  FOR INSERT TO authenticated
  WITH CHECK ((SELECT public.authorize('admin')));
